WITH TT(TTID, TTPARENT) AS (SELECT A.ID, A.PARENT_ID
       FROM ECOLI_DATA A JOIN ECOLI_DATA B ON A.PARENT_ID = B.ID
       WHERE B.PARENT_ID IS NULL)

SELECT E.ID
FROM ECOLI_DATA E JOIN TT T ON E.PARENT_ID = T.TTID
ORDER BY E.ID ASC;