SELECT A.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO A JOIN ITEM_TREE B ON A.ITEM_ID = B.ITEM_ID
WHERE A.ITEM_ID NOT IN (SELECT C.PARENT_ITEM_ID
                        FROM ITEM_TREE C
                       WHERE C.PARENT_ITEM_ID IS NOT NULL)
ORDER BY ITEM_ID DESC;