# GROUP BY 사용 방법
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE,FAVORITES) 
IN 
(
    SELECT FOOD_TYPE, MAX(FAVORITES) 
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;

# GROUP BY 사용 안한 방법

# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# FROM REST_INFO A
# WHERE (FOOD_TYPE,FAVORITES) 
# IN 
# (
#     SELECT FOOD_TYPE, MAX(FAVORITES) 
#     FROM REST_INFO B
#     WHERE A.FOOD_TYPE = B.FOOD_TYPE 
# )
# ORDER BY FOOD_TYPE DESC;