SELECT A.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(REVIEW_SCORE, 2) AS SCORE
FROM REST_INFO A JOIN (SELECT REST_ID, AVG(REVIEW_SCORE) AS REVIEW_SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID) B ON A.REST_ID = B.REST_ID
WHERE ADDRESS LIKE '서울%'
ORDER BY SCORE desc, FAVORITES desc;