WITH RECURSIVE ANCESTOR AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION
    SELECT C.ID, C.PARENT_ID, (A.GENERATION + 1) AS GENERATION
    FROM ECOLI_DATA C, ANCESTOR A
    WHERE C.PARENT_ID = A.ID
)
SELECT COUNT(*) AS COUNT, GENERATION
FROM ANCESTOR
WHERE ID NOT IN (SELECT PARENT_ID FROM ANCESTOR WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION