#자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서 
#대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 
#대여 기록 ID와 대여 금액 리스트를 출력하는 SQL문을 작성해주세요. 
#결과는 대여 금액을 기준으로 내림차순 정렬하고, 대여 금액이 같은 경우 대여 기록 ID를 기준으로 내림차순 정렬해주세요.
SELECT HISTORY_ID,
ROUND((DATEDIFF(END_DATE, START_DATE) + 1) * DAILY_FEE * ((100 - IFNULL(DISCOUNT_RATE, 0))/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE AND
((DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 7 AND 29) AND DURATION_TYPE = '7일 이상' OR
(DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 30 AND 89) AND DURATION_TYPE = '30일 이상' OR
(DATEDIFF(END_DATE, START_DATE) + 1 >= 90) AND DURATION_TYPE = '90일 이상' )
WHERE A.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;

