WITH TEMP AS (SELECT MAX(SIZE_OF_COLONY) AS MX, YEAR(DIFFERENTIATION_DATE) AS YEAR
          FROM ECOLI_DATA
          GROUP BY YEAR(DIFFERENTIATION_DATE))
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MX-SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA A, TEMP B
WHERE YEAR(DIFFERENTIATION_DATE) = YEAR
ORDER BY YEAR, YEAR_DEV;
